### ISSUE TITLE
Too many packets when bot close to their penalty area

### ISSUE THREAD

**Issue by nabeya11** [TIGERs-Mannheim/AutoReferee#7]
Game state : out of play (after stop command)
Too many packets are sent when a bot stay beside penalty area.
That cause to crash game-controller...

As We use your AutoReferee for Robocup JapanOpen2024(4/27-29), we hope it will be fixed.
Thanks!

**Comment by g3force** [comment]
Do you have any reference, like logs or screenshots?

The rules do not allow bots to stay near the opponent defense area, even during stop. If a robot keeps staying there, a foul is issued every two seconds. Is the autoRef sending fouls more frequently?

The GC can indeed not handle too many fouls in one stop phase well. However, it should still react and if you continue the match, it should work normally again. Also note, that some software, like the ssl-status-board, is quite a small message data buffer, so larger referee message (with many fouls) my not be parsed successfully.

**Comment by nabeya11** [comment]
> The rules do not allow bots to stay near the opponent defense area, even during stop. If a robot keeps staying there, a foul is issued every two seconds. Is the autoRef sending fouls more frequently?

Yes, but we met a situation like the following image:
![Screenshot from 2024-04-30 22-42-36](https://github.com/TIGERs-Mannheim/AutoReferee/assets/37445609/63bea476-12f7-400b-943f-960fae719472)

1. Blue bots were near the penalty line in inplay
1. While it switched to out-of-play, yellow bots surrounded blue ones
1. The blue team's AI tries to avoid yellow bots and (unfortunately) also their penalty zone
1. As a result, blue bots near the penalty line got stuck

<details>
<summary>console log of game controller(click)</summary>

```
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 127.0.0.1:36849
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 192.168.10.104:44005
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 172.17.0.1:52573
2024/04/30 22:39:43 Could not write referee message: write udp 192.168.10.104:44005->224.5.23.1:10003: write: no buffer space available
2024/04/30 22:39:43 Could not write referee message: write udp 172.17.0.1:52573->224.5.23.1:10003: use of closed network connection
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 127.0.0.1:57365
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 192.168.10.104:36331
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 172.17.0.1:48016
2024/04/30 22:39:43 Could not write referee message: write udp 192.168.10.104:36331->224.5.23.1:10003: write: no buffer space available
2024/04/30 22:39:43 Could not write referee message: write udp 172.17.0.1:48016->224.5.23.1:10003: use of closed network connection
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 127.0.0.1:38003
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 192.168.10.104:50550
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 172.17.0.1:38187
2024/04/30 22:39:43 Could not write referee message: write udp 192.168.10.104:50550->224.5.23.1:10003: write: no buffer space available
2024/04/30 22:39:43 Could not write referee message: write udp 172.17.0.1:38187->224.5.23.1:10003: use of closed network connection
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 127.0.0.1:59351
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 192.168.10.104:52249
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 172.17.0.1:33855
2024/04/30 22:39:43 Could not write referee message: write udp 192.168.10.104:52249->224.5.23.1:10003: write: no buffer space available
2024/04/30 22:39:43 Could not write referee message: write udp 172.17.0.1:33855->224.5.23.1:10003: use of closed network connection
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 127.0.0.1:45202
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 192.168.10.104:33402
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 172.17.0.1:37907
2024/04/30 22:39:43 Could not write referee message: write udp 192.168.10.104:33402->224.5.23.1:10003: write: no buffer space available
2024/04/30 22:39:43 Could not write referee message: write udp 172.17.0.1:37907->224.5.23.1:10003: use of closed network connection
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 127.0.0.1:37482
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 192.168.10.104:39806
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 172.17.0.1:42062
2024/04/30 22:39:43 Could not write referee message: write udp 192.168.10.104:39806->224.5.23.1:10003: write: no buffer space available
2024/04/30 22:39:43 Could not write referee message: write udp 172.17.0.1:42062->224.5.23.1:10003: use of closed network connection
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 127.0.0.1:40962
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 192.168.10.104:43606
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 172.17.0.1:47839
2024/04/30 22:39:43 Could not write referee message: write udp 192.168.10.104:43606->224.5.23.1:10003: write: no buffer space available
2024/04/30 22:39:43 Could not write referee message: write udp 172.17.0.1:47839->224.5.23.1:10003: use of closed network connection
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 127.0.0.1:38991
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 192.168.10.104:38916
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 172.17.0.1:35141
2024/04/30 22:39:43 Could not write referee message: write udp 192.168.10.104:38916->224.5.23.1:10003: write: no buffer space available
2024/04/30 22:39:43 Could not write referee message: write udp 172.17.0.1:35141->224.5.23.1:10003: use of closed network connection
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 127.0.0.1:57840
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 192.168.10.104:50161
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 172.17.0.1:50117
2024/04/30 22:39:43 Could not write referee message: write udp 192.168.10.104:50161->224.5.23.1:10003: write: no buffer space available
2024/04/30 22:39:43 Could not write referee message: write udp 172.17.0.1:50117->224.5.23.1:10003: use of closed network connection
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 127.0.0.1:38360
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 192.168.10.104:32769
2024/04/30 22:39:43 Publishing referee messages to 224.5.23.1:10003 at 172.17.0.1:51152
2024/04/30 22:39:43 Could not write referee message: write udp 192.168.10.104:32769->224.5.23.1:10003: write: no buffer space available
2024/04/30 22:39:43 Could not write referee message: write udp 172.17.0.1:51152->224.5.23.1:10003: use of closed network connection
```

</details>
<details>
<summary>console log of Autoreferee(click)</summary>

```
	at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:355) ~[protobuf-java-3.23.2.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcRefereeMessage$Referee.parseFrom(SslGcRefereeMessage.java:5541) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.source.NetworkRefereeReceiver.run(NetworkRefereeReceiver.java:105) [moduli-referee.jar:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
2024-04-30 22:48:40,039 ERROR [External Referee|NetworkRefereeReceiver] Could not read referee message
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:115) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2385) ~[protobuf-java-3.23.2.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcGameEvent$GameEvent$Builder.mergeFrom(SslGcGameEvent.java:45821) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcGameEvent$GameEvent$1.parsePartialFrom(SslGcGameEvent.java:53062) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcGameEvent$GameEvent$1.parsePartialFrom(SslGcGameEvent.java:53054) ~[moduli-referee.jar:?]
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2397) ~[protobuf-java-3.23.2.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcRefereeMessage$Referee$Builder.mergeFrom(SslGcRefereeMessage.java:6104) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcRefereeMessage$Referee$1.parsePartialFrom(SslGcRefereeMessage.java:7803) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcRefereeMessage$Referee$1.parsePartialFrom(SslGcRefereeMessage.java:7795) ~[moduli-referee.jar:?]
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:215) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:232) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:237) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:355) ~[protobuf-java-3.23.2.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcRefereeMessage$Referee.parseFrom(SslGcRefereeMessage.java:5541) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.source.NetworkRefereeReceiver.run(NetworkRefereeReceiver.java:105) [moduli-referee.jar:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
2024-04-30 22:48:40,065 ERROR [External Referee|NetworkRefereeReceiver] Could not read referee message
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:115) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2385) ~[protobuf-java-3.23.2.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcGameEvent$GameEvent$Builder.mergeFrom(SslGcGameEvent.java:45821) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcGameEvent$GameEvent$1.parsePartialFrom(SslGcGameEvent.java:53062) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcGameEvent$GameEvent$1.parsePartialFrom(SslGcGameEvent.java:53054) ~[moduli-referee.jar:?]
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2397) ~[protobuf-java-3.23.2.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcRefereeMessage$Referee$Builder.mergeFrom(SslGcRefereeMessage.java:6104) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcRefereeMessage$Referee$1.parsePartialFrom(SslGcRefereeMessage.java:7803) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcRefereeMessage$Referee$1.parsePartialFrom(SslGcRefereeMessage.java:7795) ~[moduli-referee.jar:?]
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:215) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:232) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:237) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:355) ~[protobuf-java-3.23.2.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcRefereeMessage$Referee.parseFrom(SslGcRefereeMessage.java:5541) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.source.NetworkRefereeReceiver.run(NetworkRefereeReceiver.java:105) [moduli-referee.jar:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
2024-04-30 22:48:40,091 ERROR [External Referee|NetworkRefereeReceiver] Could not read referee message
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:115) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2385) ~[protobuf-java-3.23.2.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcGameEvent$GameEvent$Builder.mergeFrom(SslGcGameEvent.java:45821) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcGameEvent$GameEvent$1.parsePartialFrom(SslGcGameEvent.java:53062) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcGameEvent$GameEvent$1.parsePartialFrom(SslGcGameEvent.java:53054) ~[moduli-referee.jar:?]
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2397) ~[protobuf-java-3.23.2.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcRefereeMessage$Referee$Builder.mergeFrom(SslGcRefereeMessage.java:6104) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcRefereeMessage$Referee$1.parsePartialFrom(SslGcRefereeMessage.java:7803) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcRefereeMessage$Referee$1.parsePartialFrom(SslGcRefereeMessage.java:7795) ~[moduli-referee.jar:?]
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:215) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:232) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:237) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48) ~[protobuf-java-3.23.2.jar:?]
	at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:355) ~[protobuf-java-3.23.2.jar:?]
	at edu.tigers.sumatra.referee.proto.SslGcRefereeMessage$Referee.parseFrom(SslGcRefereeMessage.java:5541) ~[moduli-referee.jar:?]
	at edu.tigers.sumatra.referee.source.NetworkRefereeReceiver.run(NetworkRefereeReceiver.java:105) [moduli-referee.jar:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

</details>
<details>
<summary>Packet capture(click)</summary>

```
No. Time    Source  Destination Protocol    Length  Info
418366  1678.210210397  192.168.10.104  224.5.23.1  UDP 1312    44090 → 10003 Len=19030
418373  1678.210315939  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=0, ID=3e40) [Reassembled in #418385]
418374  1678.210316162  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=1480, ID=3e40) [Reassembled in #418385]
418375  1678.210398473  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=2960, ID=3e40) [Reassembled in #418385]
418376  1678.210398691  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=4440, ID=3e40) [Reassembled in #418385]
418377  1678.210398924  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=5920, ID=3e40) [Reassembled in #418385]
418378  1678.210399150  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=7400, ID=3e40) [Reassembled in #418385]
418379  1678.210399374  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=8880, ID=3e40) [Reassembled in #418385]
418380  1678.210399608  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=10360, ID=3e40) [Reassembled in #418385]
418381  1678.210399833  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=11840, ID=3e40) [Reassembled in #418385]
418382  1678.210400060  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=13320, ID=3e40) [Reassembled in #418385]
418383  1678.210481583  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=14800, ID=3e40) [Reassembled in #418385]
418384  1678.210481815  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=16280, ID=3e40) [Reassembled in #418385]
418385  1678.210482037  192.168.10.104  224.5.23.1  UDP 1312    44090 → 10003 Len=19030
418396  1678.210627829  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=0, ID=3e41) [Reassembled in #418408]
418397  1678.210628044  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=1480, ID=3e41) [Reassembled in #418408]
418398  1678.210628317  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=2960, ID=3e41) [Reassembled in #418408]
418399  1678.210762986  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=4440, ID=3e41) [Reassembled in #418408]
418400  1678.210763307  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=5920, ID=3e41) [Reassembled in #418408]
418401  1678.210763592  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=7400, ID=3e41) [Reassembled in #418408]
418402  1678.210763895  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=8880, ID=3e41) [Reassembled in #418408]
418403  1678.210764224  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=10360, ID=3e41) [Reassembled in #418408]
418404  1678.210764568  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=11840, ID=3e41) [Reassembled in #418408]
418405  1678.210764849  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=13320, ID=3e41) [Reassembled in #418408]
418406  1678.210765182  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=14800, ID=3e41) [Reassembled in #418408]
418407  1678.210850167  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=16280, ID=3e41) [Reassembled in #418408]
418408  1678.210850516  192.168.10.104  224.5.23.1  UDP 1312    44090 → 10003 Len=19030
418415  1678.217710425  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=0, ID=3e42) [Reassembled in #418427]
418416  1678.217710798  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=1480, ID=3e42) [Reassembled in #418427]
418417  1678.217711029  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=2960, ID=3e42) [Reassembled in #418427]
418418  1678.217711255  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=4440, ID=3e42) [Reassembled in #418427]
418419  1678.217711479  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=5920, ID=3e42) [Reassembled in #418427]
418420  1678.217711703  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=7400, ID=3e42) [Reassembled in #418427]
418421  1678.217711925  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=8880, ID=3e42) [Reassembled in #418427]
418422  1678.217712173  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=10360, ID=3e42) [Reassembled in #418427]
418423  1678.217823967  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=11840, ID=3e42) [Reassembled in #418427]
418424  1678.217824203  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=13320, ID=3e42) [Reassembled in #418427]
418425  1678.217824487  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=14800, ID=3e42) [Reassembled in #418427]
418426  1678.217824711  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=16280, ID=3e42) [Reassembled in #418427]
418427  1678.217824930  192.168.10.104  224.5.23.1  UDP 1312    44090 → 10003 Len=19030
418434  1678.412804502  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=0, ID=3e43) [Reassembled in #418446]
418435  1678.412804994  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=1480, ID=3e43) [Reassembled in #418446]
418436  1678.412805174  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=2960, ID=3e43) [Reassembled in #418446]
418437  1678.412805364  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=4440, ID=3e43) [Reassembled in #418446]
418438  1678.412805540  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=5920, ID=3e43) [Reassembled in #418446]
418439  1678.412805719  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=7400, ID=3e43) [Reassembled in #418446]
418440  1678.412805898  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=8880, ID=3e43) [Reassembled in #418446]
418441  1678.412806086  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=10360, ID=3e43) [Reassembled in #418446]
418442  1678.412885079  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=11840, ID=3e43) [Reassembled in #418446]
418443  1678.412885269  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=13320, ID=3e43) [Reassembled in #418446]
418444  1678.412885490  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=14800, ID=3e43) [Reassembled in #418446]
418445  1678.412885674  192.168.10.104  224.5.23.1  IPv4    1514    Fragmented IP protocol (proto=UDP 17, off=16280, ID=3e43) [Reassembled in #418446]
```

</details>

> The GC can indeed not handle too many fouls in one stop phase well. However, it should still react and if you continue the match, it should work normally again. Also note, that some software, like the ssl-status-board, is quite a small message data buffer, so larger referee message (with many fouls) my not be parsed successfully.

The gc's UI was unresponsive when the situation occurred in the convention.
But when I check this situation afterward, I can move on to the next stage...

**Comment by g3force** [comment]
Thx for the detailed report.

Regarding the rules: It is expected, that the human ref (with the help of the GCO) detects such a situation and clears it (for example by halting the game and moving the robots manually). Afterwards, the match state should be reverted to a previous state to remove the exessive fouls. The GC and autoRef act according to the rules. We can think about a better definition of the rule for next year, but for this year, it has to be handled manually.

Regarding the errors: There is a fixed-sized read and write buffer for sending and receiving referee messages. If the referee message is too large, they can not be received or sent anymore. This is what happened in the logs. It is not about "too many packets", but about "too large packets". We run into this issue once at German Open as well and I already have it on my list to limit the referee message size to avoid such issues.

Regarding the UI: In my tests, the UI was always responsive and I was able to revert to a previous state without the excessive fouls and with that, everything worked again. Not sure why it crashed during your tournament :thinking:

**Comment by nabeya11** [comment]
Thank you for your kind reply.

We managed to continue game with human intervention.

>We run into this issue once at German Open as well and I already have it on my list to limit the referee message size to avoid such issues.

:+1: 

Regarding the UI: I suggest that it occureded with the enviroment of the tournament (remote controller, or other teams AI...?)
We will continue to closely monitor, Thanks.

If there is nothing in particular, I will close this issue in several days!
